services:
  iris-em:
    image: ${IMAGE_IRIS_EM} # EXTENDED MAINTENANCE
    init: true
    container_name: ${CONTAINER_IRIS_EM}
    hostname: ${CONTAINER_IRIS_EM}
    volumes:
    - ./IRIS:/IRIS
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    command: --key /IRIS/key/iris.key 
    ports:
      - 12001:1972
    environment:
      - ISC_DATA_DIRECTORY=/IRIS/${EXTENDED_MAINTENANCE}
      - ISC_CPF_MERGE_FILE=/IRIS/merge-em.cpf
      # - TZ=Europe/Paris

  iris-cd:
    image: ${IMAGE_IRIS_CD} # CONTINUOUS DELIVERY
    init: true
    container_name: ${CONTAINER_IRIS_CD}
    hostname: ${CONTAINER_IRIS_CD}
    volumes:
    - ./IRIS:/IRIS
    command: --key /IRIS/key/iris.key 
    ports:
      - 12002:1972
    environment:
      - ISC_DATA_DIRECTORY=/IRIS/${CONTINUOUS_DELIVERY}
      - ISC_CPF_MERGE_FILE=/IRIS/merge-cd.cpf
      - TZ=Europe/Paris

  iris-preview:
    image: ${IMAGE_IRIS_PREVIEW} # DEVELOPER PREVIEW
    init: true
    container_name: ${CONTAINER_IRIS_PREVIEW}
    hostname: ${CONTAINER_IRIS_PREVIEW}
    volumes:
    - ./IRIS:/IRIS
    command: --key /IRIS/key/iris.key 
    ports:
      - 12003:1972
    environment:
      - ISC_DATA_DIRECTORY=/IRIS/${DEVELOPER_PREVIEW}
      - ISC_CPF_MERGE_FILE=/IRIS/merge-preview.cpf
      - TZ=Europe/Paris

  webgateway:
    image: ${WEBGATEWAY}
    init: true
    hostname: ${WEBGATEWAY_NAME}
    ports:
    - ${WEBGATEWAY_PORT_HTTP}:80
    - ${WEBGATEWAY_PORT_HTTPS}:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway/CSP.ini
    volumes:
    - ./webgateway:/webgateway